{
 "title": "Battery",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Total",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (le) (increase(battery_consumption_bucket{}[1d]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(battery_consumption_sum{}[1d])) / sum(increase(battery_consumption_count{}[1d]))",
     "legendFormat": "Average battery consumption in %"
    }
   ]
  },
  {
   "title": "Android",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (le) (increase(battery_consumption_bucket{os=\"Android\"}[1d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "iOS",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by (le) (increase(battery_consumption_bucket{os=\"iOS\"}[1d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Android",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(increase(battery_consumption_sum{os=\"Android\"}[1d])) / sum(increase(battery_consumption_count{os=\"Android\"}[1d]))",
     "legendFormat": "Average battery consumption in %"
    }
   ]
  },
  {
   "title": "iOS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(increase(battery_consumption_sum{os=\"iOS\"}[1d])) / sum(increase(battery_consumption_count{os=\"iOS\"}[1d]))",
     "legendFormat": "Average battery consumption in %"
    }
   ]
  },
  {
   "title": "Dark Mode",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by (le) (increase(battery_consumption_bucket{is_dark=\"True\"}[1d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Light Mode",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "sum by (le) (increase(battery_consumption_bucket{is_dark=\"False\"}[1d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dark Mode",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum(increase(battery_consumption_sum{is_dark=\"True\"}[1d])) / sum(increase(battery_consumption_count{is_dark=\"True\"}[1d]))",
     "legendFormat": "Average battery consumption in %"
    }
   ]
  },
  {
   "title": "Light Mode",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "sum(increase(battery_consumption_sum{is_dark=\"False\"}[1d])) / sum(increase(battery_consumption_count{is_dark=\"False\"}[1d])) ",
     "legendFormat": "Average battery consumption in %"
    }
   ]
  },
  {
   "title": "Battery Saving Mode",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "sum by (le) (increase(battery_consumption_bucket{save_battery=\"True\"}[1d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "No Battery Saving Mode",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "sum by (le) (increase(battery_consumption_bucket{save_battery=\"False\"}[1d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Battery Saving Mode",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "sum(increase(battery_consumption_sum{save_battery=\"True\"}[1d])) / sum(increase(battery_consumption_count{save_battery=\"True\"}[1d]))",
     "legendFormat": "Average battery consumption in %"
    }
   ]
  },
  {
   "title": "No Battery Saving Mode",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "sum(increase(battery_consumption_sum{save_battery=\"False\"}[1d])) / sum(increase(battery_consumption_count{save_battery=\"False\"}[1d]))",
     "legendFormat": "Average battery consumption in %"
    }
   ]
  }
 ]
}