{
 "title": "Demo Zwischenpräsentation",
 "time": { "from": "now-6M", "to": "now" },
 "panels": [
  {
   "title": "Visualization of one track",
   "type": "geomap",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "1" }, "type": "logs" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Crossings usage",
   "type": "geomap",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data.metadata.routes.route.crossings.name.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" },
      {
       "field": "data.metadata.routes.route.crossings.position.lat",
       "id": "4",
       "type": "max"
      },
      {
       "field": "data.metadata.routes.route.crossings.position.lon",
       "id": "5",
       "type": "max"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Rider speed ranking",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data.metadata.userId.keyword",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "1",
        "order": "desc",
        "orderBy": "1",
        "size": "15"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "data.gps.speed", "id": "1", "settings": { "script": "_value * 3.6" }, "type": "avg" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Usage by Bike Type",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data.metadata.bikeType.keyword",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "unknown",
        "order": "desc",
        "orderBy": "1",
        "size": "0"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Rider speed ranking",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data.metadata.bikeType.keyword",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "unknown",
        "order": "desc",
        "orderBy": "1",
        "size": "0"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "data.gps.speed", "id": "1", "settings": { "script": "_value * 3.6" }, "type": "avg" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "New Panel",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data.metadata.routes.route.path.instructions.street_name.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Daily Rides",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}