{
 "title": "Docker Swarm Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Service status",
   "type": "state-timeline",
   "gridPos": { "h": 18, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "1 - service_is_up{} - (service_is_partially_running{} * 0.5)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Node Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 14, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_active", "legendFormat": "{{node}}" }
   ]
  },
  {
   "title": "Running Containers per Node",
   "type": "stat",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_running_containers", "legendFormat": "{{node}}" }
   ]
  },
  {
   "title": "Shutdown Containers per Node",
   "type": "stat",
   "gridPos": { "h": 4, "w": 14, "x": 10, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_shutdown_containers", "legendFormat": "{{node}}" }
   ]
  },
  {
   "title": "Service Replicas",
   "type": "stat",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "service_replicas", "legendFormat": "{{service}}" }
   ]
  }
 ]
}