{
 "title": "Priobike",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Main Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Service status",
   "type": "state-timeline",
   "gridPos": { "h": 20, "w": 10, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "1 - service_is_up{} - (service_is_partially_running{} * 0.5)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Status Monitor Updates",
   "type": "stat",
   "gridPos": { "h": 2, "w": 14, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "changes(stack_metrics_updated_at[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 14, "x": 10, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_active", "legendFormat": "{{node}}" }
   ]
  },
  {
   "title": "Running Containers per Node",
   "type": "stat",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_running_containers", "legendFormat": "{{node}}" }
   ]
  },
  {
   "title": "Shutdown Containers per Node",
   "type": "stat",
   "gridPos": { "h": 4, "w": 14, "x": 10, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_shutdown_containers", "legendFormat": "{{node}}" }
   ]
  },
  {
   "title": "Service Replicas",
   "type": "stat",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "service_replicas", "legendFormat": "{{service}}" }
   ]
  },
  {
   "title": "Prediction Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {}
   ]
  },
  {
   "title": "MQTT Messages for Traffic Lights from SensorThings Broker",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(prediction_service_connection_observations_count_total{}[120s]) / 2",
     "legendFormat": "Phase Changes"
    },
    {
     "expr": "increase(prediction_service_cycle_time_observations_count_total{}[120s]) / 2",
     "legendFormat": "End of a Cycle"
    },
    {
     "expr": "increase(prediction_service_program_observations_count_total{}[120s]) / 2",
     "legendFormat": "Program Changes"
    }
   ]
  },
  {
   "title": "Subscriptions per minute",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 22 },
   "targets": [
    {
     "expr": "increase(prediction_service_subscribe_count_total{}[120s])",
     "legendFormat": "Subscribe"
    },
    {
     "expr": "increase(prediction_service_unsubscribe_count_total{}[120s])",
     "legendFormat": "Unsubscribe"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prediction_service_subscription_count_total{}",
     "legendFormat": "Total Subscriptions"
    }
   ]
  },
  {
   "title": "Published Predictions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(prediction_service_predictions_count_total{}[120s]) / 2",
     "legendFormat": "Published Predictions"
    }
   ]
  },
  {
   "title": "Prediction Calc. per minute",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(prediction_service_prediction_calculations_count_total{}[1m])",
     "legendFormat": "Prediction Calculations"
    }
   ]
  },
  {
   "title": "Average Prediction Quality",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "increase(prediction_service_prediction_quality_distribution_bucket{le!=\"+Inf\"}[120s])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Datastream Subscriptions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prediction_service_subscribe_count_total{} - prediction_service_unsubscribe_count_total{}"
    }
   ]
  },
  {
   "title": "Prediction Calc. Time (ms)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prediction_calculation_timer_seconds_max{} * 1000"
    }
   ]
  },
  {
   "title": "Things that received an observation in the last 10m",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(prediction_service_udp_thing_status) / count(count by (thing_id) (prediction_service_udp_thing_status))"
    }
   ]
  },
  {
   "title": "Prediction Service Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "{service=\"staging_staging-prediction-service\"} |= ``",
     "maxLines": 5000
    }
   ]
  },
  {
   "title": "Tracking",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Devices & OS (without debug)",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 5, "x": 0, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "n_tracks_by_device_type{debug=\"false\"}",
     "legendFormat": "{{device_type}}"
    }
   ]
  },
  {
   "title": "Number of valid Tracks",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "n_tracks{debug=\"false\"}",
     "legendFormat": "Tracks"
    },
    {
     "expr": "n_tracks{debug=\"true\"}",
     "legendFormat": "Tracks Debug"
    }
   ]
  },
  {
   "title": "Unique Users over Time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "n_users{debug=\"false\"}",
     "legendFormat": "Valid"
    },
    {
     "expr": "n_users{debug=\"true\"}",
     "legendFormat": "Debug"
    }
   ]
  },
  {
   "title": "In-App Rating",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 6, "x": 15, "y": 47 },
   "targets": [
    { "expr": "n_ratings", "legendFormat": "{{rating}}" }
   ]
  },
  {
   "title": "Hours of Riding",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "n_seconds_riding{debug=\"false\"} / 3600",
     "legendFormat": "Valid"
    },
    {
     "expr": "n_seconds_riding{debug=\"true\"} / 3600",
     "legendFormat": "Debug"
    }
   ]
  },
  {
   "title": "Submitted Answers for valid Tracks",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "n_answers{debug=\"false\"}",
     "legendFormat": "Valid"
    },
    {
     "expr": "n_answers{debug=\"true\"}",
     "legendFormat": "Debug"
    }
   ]
  },
  { "title": "Load", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "# App Starts (bucket-wise)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "targets": [
    { "expr": "last_status_app_starts", "legendFormat": "# App Starts (per Bucket)" },
    {
     "expr": "last_status_past_buckets_avg_cpm",
     "legendFormat": "# App Starts (past three weeks)"
    }
   ]
  },
  {
   "title": "Load Warning active",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    { "expr": "last_status_warning", "legendFormat": "Load Warning" }
   ]
  }
 ]
}