{
 "title": "Observation Monitor",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Occured in 3m timespan", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Missing observations by thing (amber too long)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "increase(monitor_observations_basic_validation{problem=\"amber_too_long_by_thing\"}[180s])",
     "legendFormat": "{{thing}}"
    }
   ]
  },
  {
   "title": "Missing observations by thing (red amber too long)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "increase(monitor_observations_basic_validation{problem=\"red_amber_too_long_by_thing\"}[180s])",
     "legendFormat": "{{thing}}"
    }
   ]
  },
  {
   "title": "Missing observations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "increase(monitor_observations_basic_validation{problem=\"amber_too_long\"}[180s])",
     "legendFormat": "Amber too long"
    },
    {
     "expr": "increase(monitor_observations_basic_validation{problem=\"red_amber_too_long\"}[180s])",
     "legendFormat": "Red amber too long"
    }
   ]
  },
  {
   "title": "Total missing observations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(increase(monitor_observations_basic_validation{problem=~\"amber_too_long|red_amber_too_long\"}[180s]) / 2)",
     "legendFormat": "Missing observations"
    }
   ]
  },
  {
   "title": "Total missing observations by thing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by(thing) (increase(monitor_observations_basic_validation{problem=~\"amber_too_long_by_thing|red_amber_too_long_by_thing\"}[180s]) / 2)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ReceivedTime - ResultTime",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "(ReceivedTime - ResultTime) (Median)",
     "type": "barchart",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sort(monitor_times{metric=\"ReceivedResultDiff\", stats=\"median\"} / 1000)"
      }
     ]
    },
    {
     "title": "(ReceivedTime - ResultTime) (Min)",
     "type": "barchart",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sort(monitor_times{metric=\"ReceivedResultDiff\", stats=\"min\"} / 1000)"
      }
     ]
    },
    {
     "title": "(ReceivedTime - ResultTime) (Max)",
     "type": "barchart",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sort(monitor_times{metric=\"ReceivedResultDiff\", stats=\"max\"} / 1000)"
      }
     ]
    },
    {
     "title": "(ReceivedTime - ResultTime)",
     "type": "histogram",
     "description": "Looked at last 10 observations for each topic",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "monitor_times{metric=\"ReceivedResultDiff\", stats=\"median\"} / 1000",
       "legendFormat": "Median"
      },
      {
       "expr": "monitor_times{metric=\"ReceivedResultDiff\", stats=\"min\"} / 1000",
       "legendFormat": "Min"
      },
      {
       "expr": "monitor_times{metric=\"ReceivedResultDiff\", stats=\"max\"} / 1000",
       "legendFormat": "Max"
      }
     ]
    }
   ]
  },
  {
   "title": "ReceivedTime - PhenomenTime",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "(ReceivedTime - PhenomenTime) (Median)",
     "type": "barchart",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sort(monitor_times{metric=\"ReceivedPhenomenDiff\", stats=\"median\"} / 1000)"
      }
     ]
    },
    {
     "title": "(ReceivedTime - PhenomenTime) (Min)",
     "type": "barchart",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sort(monitor_times{metric=\"ReceivedPhenomenDiff\", stats=\"min\"} / 1000)"
      }
     ]
    },
    {
     "title": "(ReceivedTime - PhenomenTime) (Max)",
     "type": "barchart",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sort(monitor_times{metric=\"ReceivedPhenomenDiff\", stats=\"max\"} / 1000)"
      }
     ]
    },
    {
     "title": "(ReceivedTime - PhenomenTime)",
     "type": "histogram",
     "description": "Looked at last 10 observations for each topic",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "monitor_times{metric=\"ReceivedPhenomenDiff\", stats=\"median\"} / 1000",
       "legendFormat": "Median"
      },
      {
       "expr": "monitor_times{metric=\"ReceivedPhenomenDiff\", stats=\"min\"} / 1000",
       "legendFormat": "Min"
      },
      {
       "expr": "monitor_times{metric=\"ReceivedPhenomenDiff\", stats=\"max\"} / 1000",
       "legendFormat": "Max"
      }
     ]
    }
   ]
  },
  {
   "title": "ResultTime - PhenomenTime",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "(ResultTime - PhenomenTime) (Median)",
     "type": "barchart",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sort(monitor_times{metric=\"ResultPhenomenDiff\", stats=\"median\"} / 1000)"
      }
     ]
    },
    {
     "title": "(ResultTime - PhenomenTime) (Min)",
     "type": "barchart",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sort(monitor_times{metric=\"ResultPhenomenDiff\", stats=\"min\"} / 1000)"
      }
     ]
    },
    {
     "title": "(ResultTime - PhenomenTime) (Max)",
     "type": "barchart",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sort(monitor_times{metric=\"ResultPhenomenDiff\", stats=\"max\"} / 1000)"
      }
     ]
    },
    {
     "title": "(ResultTime - PhenomenTime)",
     "type": "histogram",
     "description": "Looked at last 10 observations for each topic",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "monitor_times{metric=\"ResultPhenomenDiff\", stats=\"median\"} / 1000",
       "legendFormat": "Median"
      },
      {
       "expr": "monitor_times{metric=\"ResultPhenomenDiff\", stats=\"min\"} / 1000",
       "legendFormat": "Min"
      },
      {
       "expr": "monitor_times{metric=\"ResultPhenomenDiff\", stats=\"max\"} / 1000",
       "legendFormat": "Max"
      }
     ]
    }
   ]
  },
  {
   "title": "Total counts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total values",
     "type": "bargauge",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "monitor_observations_basic_validation{problem=\"primary_signal_unknow_topic\"}",
       "legendFormat": "Primary Signal Unknown Topic"
      },
      {
       "expr": "monitor_observations_basic_validation{problem=\"cycle_second_unknow_topic\"}",
       "legendFormat": "Cycle Second Unknow Topic"
      },
      {
       "expr": "monitor_observations_basic_validation{problem=\"signal_program_unknow_topic\"}",
       "legendFormat": "Signal Program Unknown Topic"
      },
      {
       "expr": "monitor_observations_basic_validation{problem=\"unknow_topic\"}",
       "legendFormat": "Unknown Topic"
      },
      {
       "expr": "monitor_observations_basic_validation{problem=\"unknow_schema\"}",
       "legendFormat": "Unknown Schema"
      }
     ]
    },
    {
     "title": "Total count of amber too long",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "monitor_observations_basic_validation{problem=\"amber_too_long_by_thing\"}"
      }
     ]
    },
    {
     "title": "Total count of red amber too long",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "monitor_observations_basic_validation{problem=\"red_amber_too_long_by_thing\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Occured in last 60s timespan on average",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "General Problems",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "targets": [
      {
       "expr": "increase(monitor_observations_basic_validation{problem=\"unknow_topic\"}[120s])/2",
       "legendFormat": "Unknown Topic"
      },
      {
       "expr": "increase(monitor_observations_basic_validation{problem=\"unknow_schema\"}[120s])/2",
       "legendFormat": "Unknown Schema"
      },
      {
       "expr": "increase(monitor_observations_basic_validation{problem=\"result_too_large\"}[120s])/2",
       "legendFormat": "Result too large"
      },
      {
       "expr": "increase(monitor_observations_basic_validation{problem=\"result_negative\"}[120s])/2",
       "legendFormat": "Result negative"
      }
     ]
    },
    {
     "title": "Received old observations (phenomenTime before phenomenTime of previous observation))",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "targets": [
      {
       "expr": "increase(monitor_observations_basic_validation{problem=\"old_observation\"}[120s])/2",
       "legendFormat": "Old observations"
      }
     ]
    },
    {
     "title": "Primary Signal Problems",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "increase(monitor_observations{action=\"primary_signal_received\"}[120s])/2",
       "legendFormat": "Primary Signal Total"
      },
      {
       "expr": "increase(monitor_observations_basic_validation{problem=\"primary_signal_unknow_topic\"}[120s])/2",
       "legendFormat": "Primary Signal Unknow Topic"
      }
     ]
    },
    {
     "title": "Cycle Second Problems",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "targets": [
      {
       "expr": "increase(monitor_observations{action=\"cycle_second_received\"}[120s])/2",
       "legendFormat": "Cycle Second Total"
      },
      {
       "expr": "increase(monitor_observations_basic_validation{problem=\"cycle_second_unknow_topic\"}[120s])/2",
       "legendFormat": "Cycle Second Unknow Topic"
      }
     ]
    },
    {
     "title": "Total observations",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
     "targets": [
      {
       "expr": "increase(monitor_observations{action=\"received\"}[120s])/2",
       "legendFormat": "Total"
      },
      {
       "expr": "increase(monitor_observations{action=\"primary_signal_received\"}[120s])/2",
       "legendFormat": "Primary Signal"
      },
      {
       "expr": "increase(monitor_observations{action=\"cycle_second_received\"}[120s])/2",
       "legendFormat": "Cycle Second"
      },
      {
       "expr": "increase(monitor_observations{action=\"signal_program_received\"}[120s])/2",
       "legendFormat": "Signal Program"
      }
     ]
    },
    {
     "title": "Signal Program Problems",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "targets": [
      {
       "expr": "increase(monitor_observations{action=\"signal_program_received\"}[120s])/2",
       "legendFormat": "Signal Program Total"
      },
      {
       "expr": "increase(monitor_observations_basic_validation{problem=\"signal_program_unknow_topic\"}[120s])/2",
       "legendFormat": "Signal Program Unknow Topic"
      }
     ]
    }
   ]
  }
 ]
}