{
 "title": "Predictor",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Deviation of Predictions in Seconds",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "predictor_deviation{}", "legendFormat": "{{bucket}}s" }
   ]
  },
  {
   "title": "Observations Received",
   "type": "stat",
   "gridPos": { "h": 10, "w": 10, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(predictor_observations_by_topic{}[1m])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Observations",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "predictor_observations{}", "legendFormat": "{{action}}" }
   ]
  },
  {
   "title": "Prediction Accuracy",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(predictor_correct{} / predictor_verifiable{}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg. Message Delay",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "predictor_mean_msg_delay{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "SGs Online & Having Prediction",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "predictor_verifiable{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Published Predictions per minute",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(predictor_predictions{action=\"published\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cycles",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "predictor_histories{}", "legendFormat": "{{action}}" }
   ]
  },
  {
   "title": "Average Prediction Quality",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "predictor_prediction_quality_distribution_bucket{le!=\"+Inf\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Deviation of Predictions in Seconds",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "targets": [
    { "expr": "predictor_deviation{}", "legendFormat": "{{bucket}}s" }
   ]
  }
 ]
}