{
 "title": "Prediction Service",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Subscriptions per minute",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(prediction_service_subscribe_count_total{}[120s])",
     "legendFormat": "Subscribe"
    },
    {
     "expr": "increase(prediction_service_unsubscribe_count_total{}[120s])",
     "legendFormat": "Unsubscribe"
    }
   ]
  },
  {
   "title": "Prediction Calc. per minute",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(prediction_service_prediction_calculations_count_total{}[2m]) / 2",
     "legendFormat": "Prediction Calculations"
    }
   ]
  },
  {
   "title": "MQTT Messages for Traffic Lights from SensorThings Broker",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(prediction_service_connection_observations_count_total{}[120s]) / 2",
     "legendFormat": "Phase Changes"
    },
    {
     "expr": "increase(prediction_service_cycle_time_observations_count_total{}[120s]) / 2",
     "legendFormat": "End of a Cycle"
    },
    {
     "expr": "increase(prediction_service_program_observations_count_total{}[120s]) / 2",
     "legendFormat": "Program Changes"
    }
   ]
  },
  {
   "title": "Datastream Subscriptions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prediction_service_subscribe_count_total{} - prediction_service_unsubscribe_count_total{}"
    }
   ]
  },
  {
   "title": "Prediction Calc. Time (ms)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prediction_calculation_timer_seconds_max{} * 1000"
    }
   ]
  },
  {
   "title": "Published Predictions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(prediction_service_predictions_count_total{}[120s]) / 2",
     "legendFormat": "Published Predictions"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prediction_service_subscription_count_total{}",
     "legendFormat": "Total Subscriptions"
    }
   ]
  },
  {
   "title": "Average Prediction Quality",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "increase(prediction_service_prediction_quality_distribution_bucket{le!=\"+Inf\"}[120s])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Average received observations per connection in the last 60s",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(increase(prediction_service_connection_primary_observations_count_total[120s]) / 2)",
     "legendFormat": "Published Predictions"
    }
   ]
  },
  {
   "title": "Connections that received at least one observation since startup",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(increase(prediction_service_connection_primary_observations_count_total[120s]) / 2 > 0)",
     "legendFormat": "Published Predictions"
    }
   ]
  },
  {
   "title": "Received observations in the last 60s (sum of observations received for each connections)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(prediction_service_connection_primary_observations_count_total[120s]) / 2)",
     "legendFormat": "Published Predictions"
    }
   ]
  },
  {
   "title": "DynamicTrafficData: TLS that received observations since startup",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prediction_service_tls_that_received_observations_count_total{}",
     "legendFormat": "Published Predictions"
    }
   ]
  },
  {
   "title": "Rejected Cycles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "increase(prediction_service_rejected_cycles_count_total{}[120s]) / 2",
     "legendFormat": "Rejected Cycles"
    }
   ]
  },
  {
   "title": "DynamicTrafficData class: Connections that received observations since startup",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prediction_service_connections_that_received_observations_count_total{}",
     "legendFormat": "Published Predictions"
    }
   ]
  }
 ]
}