{
 "title": "priobike tracking service",
 "time": { "from": "now-6M", "to": "now" },
 "panels": [
  {
   "title": "User overview",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data.metadata.userId.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "20" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "hide": false,
       "id": "1",
       "type": "count"
      },
      {
       "field": "data.calculated.rideDistance",
       "id": "3",
       "settings": {},
       "type": "sum"
      },
      { "field": "data.calculated.rideTime", "id": "4", "settings": { "script": "_value / (1000 * 60 * 60)" }, "type": "sum" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Rider speed ranking",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data.metadata.bikeType.keyword",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "unknown",
        "order": "desc",
        "orderBy": "1",
        "size": "0"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "data.gps.speed", "id": "1", "settings": { "script": "_value * 3.6" }, "type": "avg" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Crossings usage",
   "type": "geomap",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data.metadata.routes.route.crossings.position",
       "id": "4",
       "settings": { "precision": "12" },
       "type": "geohash_grid"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Crossings usage",
   "type": "geomap",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data.metadata.routes.route.crossings.position",
       "id": "4",
       "settings": { "precision": "12" },
       "type": "geohash_grid"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Rider speed ranking",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data.metadata.userId.keyword",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "1",
        "order": "desc",
        "orderBy": "1",
        "size": "15"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "data.gps.speed", "id": "1", "settings": { "script": "_value * 3.6" }, "type": "avg" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Routes usage",
   "type": "geomap",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "data.gps.coordinates", "id": "4", "settings": { "precision": "7" }, "type": "geohash_grid" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Usage by Bike Type",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data.metadata.bikeType.keyword",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "unknown",
        "order": "desc",
        "orderBy": "1",
        "size": "0"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "User signups",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 43 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data.metadata.userId.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "data.metadata.startTime", "id": "1", "type": "min" },
      { "field": "data.metadata.userId.keyword", "id": "4", "type": "cardinality" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "total user number",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data.metadata.userId.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "3", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "hide": true,
       "id": "3",
       "type": "count"
      },
      { "field": "data.metadata.userId.keyword", "id": "4", "type": "cardinality" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Daily user amount",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "hide": true,
       "id": "1",
       "type": "count"
      },
      {
       "field": "data.metadata.userId.keyword",
       "hide": false,
       "id": "3",
       "type": "cardinality"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "New Panel",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data.metadata.routes.route.path.instructions.street_name.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Daily Rides",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}